# Generated by Django 4.2.15 on 2024-08-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_category_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default=1, upload_to=""),
            preserve_default=False,
        ),
    ]
